stages:  
  - test        
  - build
  - deploy

lint_job:
    stage: test
    tags:
        - test
    image: python:3.12.3-slim
    script:
        - pip install -r requirements.txt
        - black --check .
        - mypy .

build_job:
  stage: build
  tags:
    - build
  image: docker:20.10
  services:
    - name: docker:20.10-dind
      alias: docker
      command: ["--tls=false"]
  variables:
    DOCKER_IMAGE: registry.gitlab.com/thetrueryan-group/shedule_parser
    DOCKER_HOST: tcp://docker:2375  
    DOCKER_TLS_CERTDIR: ""          
  script:
    - docker build -t $DOCKER_IMAGE:$CI_COMMIT_SHORT_SHA .
    - docker tag $DOCKER_IMAGE:$CI_COMMIT_SHORT_SHA $DOCKER_IMAGE:latest  
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push $DOCKER_IMAGE:$CI_COMMIT_SHORT_SHA
    - docker push $DOCKER_IMAGE:latest 


deploy_job:
  stage: deploy
  tags:
    - deploy
  image: ubuntu:22.04
  before_script:
    - apt-get update && apt-get install -y openssh-client
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -H $SSH_SERVER_IP > ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - scp -o StrictHostKeyChecking=no ./docker-compose.yml $SSH_SERVER_USER@$SSH_SERVER_IP:~/schedule_bot/
    - ssh -o StrictHostKeyChecking=no $SSH_SERVER_USER@$SSH_SERVER_IP "cd ~/schedule_bot && docker compose down && docker compose up -d"


