stages:  
  - test        
  - build
  - deploy

lint_job:
    stage: test
    tags:
        - test
    image: python:3.12.3-slim
    script:
        - pip -r requirements.txt
        - black --check .
        - mypy .

build_job:
    stage: build
    tags:
        - build
    image: docker:20.10
    services:
        - name: docker:20.10-dind
          alias: docker
          command: ["--tls=false"]
    variables:
        DOCKER_IMAGE: registry.gitlab.com/thetrueryan/shedule_parser
        DOCKER_HOST: tcp://docker:2375
        DOCKER_TLS_CERTDIR: ""
    script:
        - docker build -t $DOCKER_IMAGE:$CI_COMMIT_SHORT_SHA .
        - docker tag $DOCKER_IMAGE:$CI_COMMIT_SHORT_SHA $DOCKER_IMAGE:latest  
        - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
        - docker push $DOCKER_IMAGE:$CI_COMMIT_SHORT_SHA
        - docker push $DOCKER_IMAGE:latest 
