services:
  db:
    image: postgres:15-alpine
    container_name: schedule_db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    restart: unless-stopped
